# Generated by Django 4.2.13 on 2024-05-20 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UdnFocus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("author", models.CharField(default="Unknown", max_length=64)),
                ("publish_time", models.DateTimeField(default=datetime.datetime.now)),
                ("content", models.TextField()),
            ],
        ),
    ]
